### ISSUE TITLE
Linear Regression Error

### ISSUE THREAD

**Issue by gkb999** [ZiluM/sacpy#1]
Hi there, 
It is a nice package and codes are easier.
But, why functions for loading the data arrays?
Also, can we use the in-built functions for different data manipulations.
Example, I tried basic "LinReg", both the data has same dimensions and still the following error pops up
![image](https://user-images.githubusercontent.com/7091088/233934670-de86cd55-c74c-4012-9596-d68316c86d5d.png)

**Comment by ZiluM** [comment]
please give me the shape of siconc and u10
















At 2023-04-24 15:58:39, "GK" ***@***.***> wrote:

Hi there,
It is a nice package and codes are easier.
But, why functions for loading the data arrays?
Also, can we use the in-built functions for different data manipulations.
Example, I tried basic "LinReg", both the data has same dimensions and still the following error pops up

**Comment by gkb999** [comment]
That's really quick.
The shapes are as follows:
1)
[image: image.png]
2)
[image: image.png]
3)
[image: image.png]

I thought the first variable's latitudes weren't matching, so I used the
third one, yet, the same error persists.

Thanks for getting back :)

G*irija Kalyani Burada*

*Doctoral StudentNew Zealand*

**Comment by ZiluM** [comment]
I can't see the image.png, please copy or upload a new one! Thank you!
I think the quick fix is switching the sconce and u10's locations.

**Comment by gkb999** [comment]
1) sic= xarray.DataArray  time: 516      latitude: 361      longitude: 1440
2) u10 =
 xarray.DataArray    time: 516        latitude: 281  longitude: 1440
3) z = xarray.DataArray'z'time: 516       latitude: 281         longitude:
1440

These are the quick sizes, plus, shift the location to? Package's folder?

**Comment by ZiluM** [comment]
I think you have not understood the function of LinReg. It calculates the Y = aX + b, X is one dim and Y is one or two or three or more dims (plz see the documents). 
If you want to calculate the space correlation in each space point, I will add this function in the next version!


Zilu Meng
















At 2023-04-24 16:21:40, "GK" ***@***.***> wrote:

1) sic= xarray.DataArray time: 516 latitude: 361 longitude: 1440
2) u10 =
xarray.DataArray time: 516 latitude: 281 longitude: 1440
3) z = xarray.DataArray'z'time: 516 latitude: 281 longitude:
1440

These are the quick sizes, plus, shift the location to? Package's folder?

**Comment by gkb999** [comment]
I see, Thanks for the clarification.
Let me know when the space correlation at each point is added :) - would be interested in testing.
