### ISSUE TITLE
关于库的名字

### ISSUE THREAD

**Issue by jesieleo** [ZiluM/sacpy#3]
首先感谢大佬，这个库填补了目前python的空缺，但由于其名字与诸如scapy等库太像，在浏览器上常常搜索不到，请问有什么办法改善吗？

**Comment by ZiluM** [comment]
可以加上我的名字 zilumeng



---- 回复的原邮件 ----
| 发件人 | Liu ***@***.***> |
| 日期 | 2023年05月19日 15:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [ZiluM/sacpy] 关于库的名字 (Issue #3) |

首先感谢大佬，这个库填补了目前python的空缺，但由于其名字与诸如scapy等库太像，在浏览器上常常搜索不到，请问有什么办法改善吗？
